repos:
  - repo: https://github.com/ambv/black
    rev: 23.1a1
    hooks:
      - id: black
        language_version: python3.10
        args: [--config=python-fmt-conf/pyproject.toml]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-freezegun, types-paramiko, types-PyYAML, types-pytz, types-boto] 